/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/emma.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { button, useControls } from "leva";
import React, { useEffect, useRef, useState } from "react";

import * as THREE from "three";
import { useChat } from "../hooks/useChat";

const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: {
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    mouthLeft: 1,
    eyeLookUpLeft: 1,
    eyeLookUpRight: 1,
    cheekPuff: 0.9999924982764238,
    mouthDimpleLeft: 0.414743888682652,
    mouthRollLower: 0.32,
    mouthSmileLeft: 0.35499733688813034,
    mouthSmileRight: 0.35499733688813034,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78341,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.351,
    mouthFunnel: 1,
    browInnerUp: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: {
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.5700000000000001,
    noseSneerRight: 0.51,
    eyeLookDownLeft: 0.39435766259644545,
    eyeLookUpRight: 0.4039761421719682,
    eyeLookInLeft: 0.9618479575523053,
    eyeLookInRight: 0.9618479575523053,
    jawOpen: 0.9618479575523053,
    mouthDimpleLeft: 0.9618479575523053,
    mouthDimpleRight: 0.9618479575523053,
    mouthStretchLeft: 0.27893590769016857,
    mouthStretchRight: 0.2885543872656917,
    mouthSmileLeft: 0.5578718153803371,
    mouthSmileRight: 0.38473918302092225,
    tongueOut: 0.9618479575523053,
  },
};

const corresponding = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
};

let setupMode = false;

// Variable global para rastrear si el contexto de audio ha sido inicializado
let audioContextInitialized = false;

export function Avatar(props) {
  const { nodes, materials, scene } = useGLTF(
    "/models/emma.glb"
  );

  const { message, onMessagePlayed, chat } = useChat();

  const [lipsync, setLipsync] = useState();
  const audioContextRef = useRef(null);

  // Mejorar calidad de materiales y texturas
  useEffect(() => {
    scene.traverse((child) => {
      if (child.isMesh && child.material) {
        const materials = Array.isArray(child.material) ? child.material : [child.material];
        materials.forEach((mat) => {
          if (mat && mat.map) {
            // Mejorar calidad de texturas
            mat.map.anisotropy = 16; // Mejor calidad de texturas
            mat.map.minFilter = THREE.LinearMipmapLinearFilter;
            mat.map.magFilter = THREE.LinearFilter;
            mat.map.generateMipmaps = true;
          }
          // Mejorar renderizado
          if (mat) {
            mat.needsUpdate = true;
          }
        });
      }
    });
  }, [scene]);

  // Función para inicializar el contexto de audio (necesario para iOS)
  const initializeAudioContext = async () => {
    if (audioContextInitialized) {
      return true;
    }
    
    // Crear un audio silencioso para activar el contexto de audio en iOS
    const silentAudio = new Audio('data:audio/wav;base64,UklGRigAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA=');
    silentAudio.volume = 0.01; // Muy bajo pero no cero (iOS a veces ignora volumen 0)
    silentAudio.setAttribute('playsinline', 'true');
    silentAudio.setAttribute('webkit-playsinline', 'true');
    
    try {
      await silentAudio.play();
      // Pausar inmediatamente después de iniciar
      silentAudio.pause();
      silentAudio.currentTime = 0;
      audioContextInitialized = true;
      return true;
    } catch (e) {
      console.warn('No se pudo inicializar el contexto de audio:', e);
      return false;
    }
  };

  useEffect(() => {
    console.log(message);
    if (!message) {
      setAnimation("Idle");
      return;
    }
    setAnimation(message.animation);
    setFacialExpression(message.facialExpression);
    setLipsync(message.lipsync);
    
    const playAudio = async () => {
      // Inicializar contexto de audio si es necesario (para iOS)
      await initializeAudioContext();
      
      // Crear el elemento de audio
      const audio = new Audio("data:audio/mp3;base64," + message.audio);
      
      // Configuraciones críticas para iOS
      audio.setAttribute('playsinline', 'true');
      audio.setAttribute('webkit-playsinline', 'true');
      audio.setAttribute('preload', 'auto');
      audio.crossOrigin = 'anonymous';
      
      // Configurar volumen
      audio.volume = 1.0;
      
      // Para iOS: asegurar que el audio se carga antes de reproducir
      audio.load();
      
      // Esperar a que el audio esté listo (especialmente importante para iOS)
      await new Promise((resolve) => {
        if (audio.readyState >= 2) {
          // HAVE_CURRENT_DATA o superior
          resolve();
        } else {
          audio.addEventListener('canplaythrough', () => resolve(), { once: true });
          audio.addEventListener('error', () => resolve(), { once: true }); // Resolver incluso si hay error
        }
      });
      
      // Intentar reproducir el audio
      try {
        const playPromise = audio.play();
        
        // Manejar la promesa de play
        if (playPromise !== undefined) {
          await playPromise;
        }
        
        setAudio(audio);
        audio.onended = () => {
          onMessagePlayed();
        };
        
        // Manejar errores durante la reproducción
        audio.onerror = (error) => {
          console.error('Error en audio durante reproducción:', error);
        };
        
      } catch (error) {
        console.error('Error reproduciendo audio:', error);
        console.error('Error details:', {
          name: error.name,
          message: error.message,
          code: error.code
        });
        
        // Si falla, intentar de nuevo después de un pequeño delay
        setTimeout(async () => {
          try {
            const playPromise = audio.play();
            if (playPromise !== undefined) {
              await playPromise;
            }
            setAudio(audio);
            audio.onended = () => {
              onMessagePlayed();
            };
          } catch (retryError) {
            console.error('Error en segundo intento de reproducir audio:', retryError);
            // Aún así, continuar con la animación aunque el audio no se reproduzca
            setAudio(audio);
            // Simular que el audio terminó para avanzar (usar duración real si está disponible)
            const estimatedDuration = audio.duration || 3;
            setTimeout(() => {
              onMessagePlayed();
            }, estimatedDuration * 1000);
          }
        }, 200);
      }
    };
    
    playAudio();
  }, [message, onMessagePlayed]);

  const { animations } = useGLTF("/models/animations.glb");

  const group = useRef();
  const { actions, mixer } = useAnimations(animations, group);
  const [animation, setAnimation] = useState(
    animations.find((a) => a.name === "Idle") ? "Idle" : animations[0].name // Check if Idle animation exists otherwise use first animation
  );
  useEffect(() => {
    if (!actions[animation]) {
      console.warn(`Animation "${animation}" not found`);
      return;
    }
    actions[animation]
      .reset()
      .fadeIn(mixer.stats.actions.inUse === 0 ? 0 : 0.5)
      .play();
    return () => {
      if (actions[animation]) {
        actions[animation].fadeOut(0.5);
      }
    };
  }, [animation, actions, mixer]);

  const lerpMorphTarget = (target, value, speed = 0.3) => {
    scene.traverse((child) => {
      if (child.isSkinnedMesh && child.morphTargetDictionary) {
        const index = child.morphTargetDictionary[target];
        if (
          index === undefined ||
          child.morphTargetInfluences[index] === undefined
        ) {
          return;
        }
        // Usar velocidad más rápida para lipsync (más responsivo)
        const lerpSpeed = target.startsWith('viseme_') ? Math.max(speed, 0.5) : speed;
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          lerpSpeed
        );

        if (!setupMode) {
          try {
            set({
              [target]: value,
            });
          } catch (e) {}
        }
      }
    });
  };

  const [blink, setBlink] = useState(false);
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);
  const [facialExpression, setFacialExpression] = useState("");
  const [audio, setAudio] = useState();

  useFrame(() => {
    !setupMode &&
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        const mapping = facialExpressions[facialExpression];
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        if (mapping && mapping[key]) {
          lerpMorphTarget(key, mapping[key], 0.2); // Más rápido para expresiones faciales
        } else {
          lerpMorphTarget(key, 0, 0.2); // Más rápido para resetear
        }
      });

    lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.6);
    lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.6);

    // LIPSYNC
    if (setupMode) {
      return;
    }

    const appliedMorphTargets = [];
    if (message && lipsync && lipsync.mouthCues && lipsync.mouthCues.length > 0) {
      // Usar datos de lip-sync reales si están disponibles
      const currentAudioTime = audio ? audio.currentTime : 0;
      
      // Buscar el mouthCue más cercano al tiempo actual
      let activeCue = null;
      let closestCue = null;
      let closestDistance = Infinity;
      
      for (let i = 0; i < lipsync.mouthCues.length; i++) {
        const mouthCue = lipsync.mouthCues[i];
        const cueStart = mouthCue.start;
        const cueEnd = mouthCue.end;
        const cueCenter = (cueStart + cueEnd) / 2;
        
        // Si estamos dentro del rango del cue, usarlo directamente
        if (currentAudioTime >= cueStart && currentAudioTime <= cueEnd) {
          activeCue = mouthCue;
          break;
        }
        
        // Si no, encontrar el más cercano para transiciones suaves
        const distance = Math.abs(currentAudioTime - cueCenter);
        if (distance < closestDistance) {
          closestDistance = distance;
          closestCue = mouthCue;
        }
      }
      
      const cueToUse = activeCue || closestCue;
      if (cueToUse && corresponding[cueToUse.value]) {
        const visemeTarget = corresponding[cueToUse.value];
        appliedMorphTargets.push(visemeTarget);
        
        // Calcular intensidad basada en la posición dentro del cue
        let intensity = 1.0;
        if (activeCue) {
          const cueDuration = activeCue.end - activeCue.start;
          const positionInCue = (currentAudioTime - activeCue.start) / cueDuration;
          // Crear una curva suave (más intenso en el centro)
          intensity = Math.sin(positionInCue * Math.PI);
        } else if (closestCue) {
          // Si está cerca pero fuera del rango, reducir intensidad
          intensity = Math.max(0, 1 - (closestDistance * 2));
        }
        
        lerpMorphTarget(visemeTarget, intensity, 0.6); // Velocidad más rápida para mejor sincronización
      }
    } else if (message && audio && !audio.paused && !audio.ended) {
      // Fallback mejorado: animación más natural basada en el audio
      const currentAudioTime = audio.currentTime;
      const audioDuration = audio.duration || 0;
      
      // Solo animar si el audio está reproduciéndose
      if (audioDuration > 0) {
        // Crear múltiples frecuencias para movimiento más natural
        const fastWave = Math.sin(currentAudioTime * 12); // Movimiento rápido
        const slowWave = Math.sin(currentAudioTime * 4); // Movimiento lento
        const combinedWave = (fastWave + slowWave) / 2;
        
        // Mapear el wave a diferentes visemes
        const visemeSequence = ['A', 'E', 'I', 'O', 'U', 'A', 'E', 'I'];
        const normalizedWave = (combinedWave + 1) / 2; // Normalizar entre 0 y 1
        const visemeIndex = Math.floor(normalizedWave * visemeSequence.length);
        const currentViseme = visemeSequence[Math.min(visemeIndex, visemeSequence.length - 1)];
        const visemeTarget = corresponding[currentViseme];
        
        if (visemeTarget) {
          appliedMorphTargets.push(visemeTarget);
          // Usar una intensidad variable más natural basada en múltiples ondas
          const intensity = 0.4 + Math.abs(combinedWave) * 0.4;
          lerpMorphTarget(visemeTarget, intensity, 0.5); // Más rápido para mejor sincronización
        }
      }
    }

    // Resetear todos los visemes que no están activos (más rápido para mejor sincronización)
    Object.values(corresponding).forEach((value) => {
      if (appliedMorphTargets.includes(value)) {
        return;
      }
      lerpMorphTarget(value, 0, 0.4); // Velocidad más rápida para resetear
    });
  });

  useControls("FacialExpressions", {
    chat: button(() => chat()),
    winkLeft: button(() => {
      setWinkLeft(true);
      setTimeout(() => setWinkLeft(false), 300);
    }),
    winkRight: button(() => {
      setWinkRight(true);
      setTimeout(() => setWinkRight(false), 300);
    }),
    animation: {
      value: animation,
      options: animations.map((a) => a.name),
      onChange: (value) => setAnimation(value),
    },
    facialExpression: {
      options: Object.keys(facialExpressions),
      onChange: (value) => setFacialExpression(value),
    },
    enableSetupMode: button(() => {
      setupMode = true;
    }),
    disableSetupMode: button(() => {
      setupMode = false;
    }),
    logMorphTargetValues: button(() => {
      const emotionValues = {};
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        const value =
          nodes.EyeLeft.morphTargetInfluences[
            nodes.EyeLeft.morphTargetDictionary[key]
          ];
        if (value > 0.01) {
          emotionValues[key] = value;
        }
      });
      console.log(JSON.stringify(emotionValues, null, 2));
    }),
  });

  const [, set] = useControls("MorphTarget", () =>
    Object.assign(
      {},
      ...Object.keys(nodes.EyeLeft.morphTargetDictionary).map((key) => {
        return {
          [key]: {
            label: key,
            value: 0,
            min: nodes.EyeLeft.morphTargetInfluences[
              nodes.EyeLeft.morphTargetDictionary[key]
            ],
            max: 1,
            onChange: (val) => {
              if (setupMode) {
                lerpMorphTarget(key, val, 1);
              }
            },
          },
        };
      })
    )
  );

  useEffect(() => {
    let blinkTimeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          nextBlink();
        }, 200);
      }, THREE.MathUtils.randInt(1000, 5000));
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="Wolf3D_Body"
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Bottom"
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Footwear"
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Top"
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Hair"
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/emma.glb");
useGLTF.preload("/models/animations.glb");
